# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from TTSTechmo.synthesize import synthesize
from TTSTechmo.settings import setup

class Ui_main_window(object):
    settings = setup()
    def SetInputText(self):
        pass
    def SetInputLanguage(self):
        pass
    def SetTranslationLanguage(self):
        pass
    def Translate(self):
        pass
    def TranslateAndSynthesize(self):
        pass
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1072, 881)
        main_window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        main_window.setDocumentMode(False)
        main_window.setDockNestingEnabled(False)
        self.main_widget = QtWidgets.QWidget(main_window)
        self.main_widget.setObjectName("main_widget")
        self.progressBar = QtWidgets.QProgressBar(self.main_widget)
        self.progressBar.setGeometry(QtCore.QRect(40, 360, 991, 41))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.textEdit = QtWidgets.QTextEdit(self.main_widget)
        self.textEdit.setGeometry(QtCore.QRect(40, 50, 991, 151))
        self.textEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.main_widget)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 550, 991, 131))
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.main_widget)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 740, 991, 91))
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_3.setObjectName("textEdit_3")
        self.comboBox = QtWidgets.QComboBox(self.main_widget)
        self.comboBox.setGeometry(QtCore.QRect(40, 260, 301, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.main_widget)
        self.comboBox_2.setGeometry(QtCore.QRect(720, 260, 301, 51))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.main_widget)
        self.label.setGeometry(QtCore.QRect(40, 320, 991, 21))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.main_widget)
        self.label_2.setGeometry(QtCore.QRect(40, 700, 991, 21))
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.main_widget)
        self.label_3.setGeometry(QtCore.QRect(40, 510, 991, 21))
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.main_widget)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 991, 21))
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.main_widget)
        self.label_5.setGeometry(QtCore.QRect(40, 220, 991, 21))
        self.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.main_widget)
        self.line.setGeometry(QtCore.QRect(350, 280, 141, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.main_widget)
        self.line_2.setGeometry(QtCore.QRect(350, 270, 141, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.main_widget)
        self.line_3.setGeometry(QtCore.QRect(570, 280, 141, 20))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.main_widget)
        self.line_4.setGeometry(QtCore.QRect(570, 270, 141, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.label_6 = QtWidgets.QLabel(self.main_widget)
        self.label_6.setGeometry(QtCore.QRect(510, 280, 47, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.main_widget)
        self.label_7.setGeometry(QtCore.QRect(490, 270, 81, 31))
        self.label_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.main_widget)
        self.pushButton.setGeometry(QtCore.QRect(40, 420, 991, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.main_widget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 460, 991, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        main_window.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.textEdit.textChanged.connect(main_window.SetInputText) # type: ignore
        self.comboBox.currentIndexChanged['QString'].connect(main_window.SetInputLanguage) # type: ignore
        self.comboBox_2.currentIndexChanged['QString'].connect(main_window.SetTranslationLanguage) # type: ignore
        self.pushButton.clicked.connect(main_window.Translate) # type: ignore
        self.pushButton_2.clicked.connect(main_window.TranslateAndSynthesize) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.comboBox.setItemText(0, _translate("main_window", "English"))
        self.comboBox.setItemText(1, _translate("main_window", "Polish"))
        self.comboBox.setItemText(2, _translate("main_window", "Spanish"))
        self.comboBox_2.setItemText(0, _translate("main_window", "English"))
        self.comboBox_2.setItemText(1, _translate("main_window", "Polish"))
        self.comboBox_2.setItemText(2, _translate("main_window", "Spanish"))
        self.label.setText(_translate("main_window", "Progress"))
        self.label_2.setText(_translate("main_window", "Translation data - info for analysis"))
        self.label_3.setText(_translate("main_window", "Output text - translation"))
        self.label_4.setText(_translate("main_window", "Input Text"))
        self.label_5.setText(_translate("main_window", "Language Pick"))
        self.label_7.setText(_translate("main_window", "To"))
        self.pushButton.setText(_translate("main_window", "Translate"))
        self.pushButton_2.setText(_translate("main_window", "Translate and Synthesize (not avalible for Spanish)"))
