# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time

from TTSTechmo.synthesize import synthesize
from TTSTechmo.settings import setup
from EasyNMT.translator_easynmt import translate
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    settings = setup()
    def SetInputText(self):
        self.settings.text_to_translate = self.input_text_line_edit.toPlainText()
    def SetInputLanguage(self):
        if self.entry_language_box.currentText() == "English":
            self.settings.language_source = 'en'
        elif self.entry_language_box.currentText() == "Polish":
            self.settings.language_source = 'pl'
        elif self.entry_language_box.currentText() == "Spanish":
            self.settings.language_source = 'es'
    def SetTranslationLanguage(self):
        if self.exit_language_box.currentText() == "English":
            self.settings.language = 'en'
            self.settings.tts_lang = 'tts-en'
        elif self.exit_language_box.currentText() == "Polish":
            self.settings.language = 'pl'
            self.settings.tts_lang = 'tts-pl'
        elif self.exit_language_box.currentText() == "Spanish":
            self.settings.language = 'es'
    def Translate(self):
        t = time.time()
        self.settings.text = translate(self.settings.text_to_translate, self.settings.language_source, self.settings.language)
        self.output_text_edit.setText(self.settings.text)
        elapsed = time.time() - t
        self.data_box.setText("Elapsed time of operation : " + str(elapsed))
    def TranslateAndSynthesize(self):
        t = time.time()
        self.settings.text = translate(self.settings.text_to_translate, self.settings.language_source, self.settings.language)
        self.output_text_edit.setText(self.settings.text)
        tsynt = time.time()
        synthesize(self.settings)
        elapsed = time.time() - t
        elapsedsynt = time.time() - tsynt
        self.data_box.setText("Elapsed time of operation : " + str(elapsed) + "/nSynthesis elapsed time : " + str(elapsedsynt) + "/nTranslation elapsed time : " + str(elapsed - elapsedsynt))
    def ReplaceLanguages(self):
        source_lang = self.entry_language_box.currentIndex()
        self.entry_language_box.setCurrentIndex(self.exit_language_box.currentIndex())
        self.exit_language_box.setCurrentIndex(source_lang)
        self.SetInputLanguage()
        self.SetTranslationLanguage()
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1072, 881)
        main_window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        main_window.setDocumentMode(False)
        main_window.setDockNestingEnabled(False)
        self.main_widget = QtWidgets.QWidget(main_window)
        self.main_widget.setObjectName("main_widget")
        self.progress_bar = QtWidgets.QProgressBar(self.main_widget)
        self.progress_bar.setGeometry(QtCore.QRect(40, 360, 991, 41))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.output_text_edit = QtWidgets.QTextEdit(self.main_widget)
        self.output_text_edit.setGeometry(QtCore.QRect(40, 550, 991, 131))
        self.output_text_edit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.output_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_text_edit.setObjectName("output_text_edit")
        self.data_box = QtWidgets.QTextEdit(self.main_widget)
        self.data_box.setGeometry(QtCore.QRect(40, 740, 991, 91))
        self.data_box.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.data_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_box.setObjectName("data_box")
        self.entry_language_box = QtWidgets.QComboBox(self.main_widget)
        self.entry_language_box.setGeometry(QtCore.QRect(40, 260, 261, 51))
        self.entry_language_box.setObjectName("entry_language_box")
        self.entry_language_box.addItem("")
        self.entry_language_box.addItem("")
        self.entry_language_box.addItem("")
        self.exit_language_box = QtWidgets.QComboBox(self.main_widget)
        self.exit_language_box.setGeometry(QtCore.QRect(680, 260, 261, 51))
        self.exit_language_box.setObjectName("exit_language_box")
        self.exit_language_box.addItem("")
        self.exit_language_box.addItem("")
        self.exit_language_box.addItem("")
        self.progress_label = QtWidgets.QLabel(self.main_widget)
        self.progress_label.setGeometry(QtCore.QRect(40, 320, 991, 21))
        self.progress_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.progress_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_label.setObjectName("progress_label")
        self.data_label = QtWidgets.QLabel(self.main_widget)
        self.data_label.setGeometry(QtCore.QRect(40, 700, 991, 21))
        self.data_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.data_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_label.setObjectName("data_label")
        self.output_text_label = QtWidgets.QLabel(self.main_widget)
        self.output_text_label.setGeometry(QtCore.QRect(40, 510, 991, 21))
        self.output_text_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.output_text_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.output_text_label.setObjectName("output_text_label")
        self.language_choice_label = QtWidgets.QLabel(self.main_widget)
        self.language_choice_label.setGeometry(QtCore.QRect(40, 220, 991, 21))
        self.language_choice_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.language_choice_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.language_choice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.language_choice_label.setObjectName("language_choice_label")
        self.line = QtWidgets.QFrame(self.main_widget)
        self.line.setGeometry(QtCore.QRect(310, 280, 141, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.main_widget)
        self.line_2.setGeometry(QtCore.QRect(310, 270, 141, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.main_widget)
        self.line_3.setGeometry(QtCore.QRect(530, 280, 141, 20))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.main_widget)
        self.line_4.setGeometry(QtCore.QRect(530, 270, 141, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.label_6 = QtWidgets.QLabel(self.main_widget)
        self.label_6.setGeometry(QtCore.QRect(470, 280, 47, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.to_label = QtWidgets.QLabel(self.main_widget)
        self.to_label.setGeometry(QtCore.QRect(450, 270, 81, 31))
        self.to_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.to_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.to_label.setAlignment(QtCore.Qt.AlignCenter)
        self.to_label.setObjectName("to_label")
        self.translate_button = QtWidgets.QPushButton(self.main_widget)
        self.translate_button.setGeometry(QtCore.QRect(40, 420, 991, 31))
        self.translate_button.setObjectName("translate_button")
        self.translate_and_synthesize_button = QtWidgets.QPushButton(self.main_widget)
        self.translate_and_synthesize_button.setGeometry(QtCore.QRect(40, 460, 991, 31))
        self.translate_and_synthesize_button.setObjectName("translate_and_synthesize_button")
        self.input_choice_widget = QtWidgets.QTabWidget(self.main_widget)
        self.input_choice_widget.setGeometry(QtCore.QRect(40, 10, 991, 191))
        self.input_choice_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.input_choice_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.input_choice_widget.setDocumentMode(True)
        self.input_choice_widget.setTabsClosable(False)
        self.input_choice_widget.setMovable(False)
        self.input_choice_widget.setTabBarAutoHide(False)
        self.input_choice_widget.setObjectName("input_choice_widget")
        self.voice_input = QtWidgets.QWidget()
        self.voice_input.setAutoFillBackground(False)
        self.voice_input.setObjectName("voice_input")
        self.input_voice_label = QtWidgets.QLabel(self.voice_input)
        self.input_voice_label.setGeometry(QtCore.QRect(10, 10, 961, 21))
        self.input_voice_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.input_voice_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_voice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_voice_label.setObjectName("input_voice_label")
        self.record_button = QtWidgets.QPushButton(self.voice_input)
        self.record_button.setGeometry(QtCore.QRect(30, 60, 75, 81))
        self.record_button.setObjectName("record_button")
        self.timer_of_recording = QtWidgets.QLCDNumber(self.voice_input)
        self.timer_of_recording.setGeometry(QtCore.QRect(130, 60, 101, 23))
        self.timer_of_recording.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.timer_of_recording.setSmallDecimalPoint(False)
        self.timer_of_recording.setMode(QtWidgets.QLCDNumber.Dec)
        self.timer_of_recording.setSegmentStyle(QtWidgets.QLCDNumber.Outline)
        self.timer_of_recording.setObjectName("timer_of_recording")
        self.input_choice_widget.addTab(self.voice_input, "")
        self.text_input = QtWidgets.QWidget()
        self.text_input.setEnabled(True)
        self.text_input.setObjectName("text_input")
        self.input_text_label = QtWidgets.QLabel(self.text_input)
        self.input_text_label.setGeometry(QtCore.QRect(10, 10, 961, 21))
        self.input_text_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.input_text_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_text_label.setObjectName("input_text_label")
        self.input_text_line_edit = QtWidgets.QTextEdit(self.text_input)
        self.input_text_line_edit.setGeometry(QtCore.QRect(10, 40, 961, 121))
        self.input_text_line_edit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.input_text_line_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_text_line_edit.setObjectName("input_text_line_edit")
        self.input_choice_widget.addTab(self.text_input, "")
        self.replace_button = QtWidgets.QPushButton(self.main_widget)
        self.replace_button.setGeometry(QtCore.QRect(950, 260, 75, 51))
        self.replace_button.setObjectName("replace_button")
        main_window.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.input_choice_widget.setCurrentIndex(1)
        self.entry_language_box.currentIndexChanged['QString'].connect(main_window.SetInputLanguage) # type: ignore
        self.exit_language_box.currentIndexChanged['QString'].connect(main_window.SetTranslationLanguage) # type: ignore
        self.translate_button.clicked.connect(main_window.Translate) # type: ignore
        self.translate_and_synthesize_button.clicked.connect(main_window.TranslateAndSynthesize) # type: ignore
        self.input_text_line_edit.textChanged.connect(main_window.SetInputText) # type: ignore
        self.replace_button.clicked.connect(main_window.ReplaceLanguages) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.entry_language_box.setItemText(0, _translate("main_window", "English"))
        self.entry_language_box.setItemText(1, _translate("main_window", "Polish"))
        self.entry_language_box.setItemText(2, _translate("main_window", "Spanish"))
        self.exit_language_box.setItemText(0, _translate("main_window", "English"))
        self.exit_language_box.setItemText(1, _translate("main_window", "Polish"))
        self.exit_language_box.setItemText(2, _translate("main_window", "Spanish"))
        self.progress_label.setText(_translate("main_window", "Progress"))
        self.data_label.setText(_translate("main_window", "Translation data - info for analysis"))
        self.output_text_label.setText(_translate("main_window", "Output text - translation"))
        self.language_choice_label.setText(_translate("main_window", "Language Choice"))
        self.to_label.setText(_translate("main_window", "To"))
        self.translate_button.setText(_translate("main_window", "Translate"))
        self.translate_and_synthesize_button.setText(_translate("main_window", "Translate and Synthesize (not avalible for Spanish)"))
        self.input_voice_label.setText(_translate("main_window", "Voice Input"))
        self.record_button.setText(_translate("main_window", "Record"))
        self.input_choice_widget.setTabText(self.input_choice_widget.indexOf(self.voice_input), _translate("main_window", "Voice Input"))
        self.input_text_label.setText(_translate("main_window", "Input Text"))
        self.input_choice_widget.setTabText(self.input_choice_widget.indexOf(self.text_input), _translate("main_window", "Text Input"))
        self.replace_button.setText(_translate("main_window", "Replace"))
